name: Maven Publish

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java SDK
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 11

      - name: Build with Maven
        env:
          USERNAME: ${{github.actor}}
          PASSWORD: ${{secrets.GITHUB_TOKEN}}
        run: |
          mvn -U -B clean verify -f backend/pom.xml --settings settings.xml
          mkdir staging
          cp backend/sirius-web-sample-application/target/sirius-web-sample-application-*-SNAPSHOT.jar staging/sirius-web-sample-application.jar

      - name: Publish
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging
